name: Python Tests

on:
  push:
    branches: [ "main", "master" ]  # Запускать при пуше в main/master
  pull_request:
    branches: [ "main", "master" ]  # И при Pull Request в эти ветки

jobs:
  test:
    runs-on: ubuntu-latest  # Используем последний Ubuntu

    steps:
    - uses: actions/checkout@v4  # Клонируем репозиторий

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"  # Указываем версию Python (можно изменить)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Устанавливаем pytest

    - name: Run tests
      run: |
        pytest test_temp_k.py -v  # Запускаем тесты
